# Generated by Django 3.1.6 on 2021-02-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weather_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='city_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
