# Generated by Django 3.1.6 on 2021-02-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.location'),
        ),
    ]
